### PR TITLE
Almost complete rewrite

### PR DESCRIPTION
**Pull request by fvdbeek**
I have almost completely rewritten garmin.py in order to support the uploading of maps.

In the process of getting to know the code, I have almost completely rewritten the code:
- improved coding style to conform to the PEP8 style guide
- improved logging
- improved docstrings
- used a factory method to create objects
- used the new PyUSB 1.0 API
- used f-strings instead of %-formatting
- used the rawutil module instead of a customized struct
- implemented unit ID request
- added support for baudrate change
- added support for proximity waypoints transfer
- added support for waypoint category transfer
- added support for position initialization
- added support for maps
- added support for image transfer (screenshots and waypoint symbols)
- added support for screenshots
- removed test code (because I believe this belongs outside the main module)
- and so much more that there are in fact few lines of code left unchanged

This pull request will break the code for packaging and the gnome-pygarmin application and the documentation will have to be rewritten. Clearly the work isn't done yet, but I want to share what I have so you can decide whether the features are worthwhile to merge with upstream, or it would be better to create a separate project as a friendly fork.

I have also rewritten pygarmin to a fairly complete command-line application to show off the new features.

### CODE REVIEW

**Comment by quentinsf** [comment]
Hi Folkert - 

That's an impressive amount of work!  Since I started pygarmin in a previous millennium, I think it's probably due for a major rewrite!

I'd be very happy to merge it in and give you commit access to the repository;  I don't have a Garmin device I could test it with any more, so testing etc would be up to you!  We could even give it a 1.0 version number on PyPI, since it's been on 0.8 for seven years!

Anyway, what I'm basically saying is that I'd be delighted for your rewrite to become the 'official' version, but I probably can't provide much help beyond the real basics.  Would you be happy with that?

All the best, and thanks!
Quentin

**Comment by fvdbeek** [comment]
That would be nice. I also prefer an update to a fork and will gladly use your repository.

**Comment by quentinsf** [comment]
Great - let me know when you're ready to do a merge, or we could set up a separate branch here for it.

**Comment by fvdbeek** [comment]
I believe the rewrite branch is ready for merging:
- Updated documentation
- Packaged the project
- Deleted the gnome-pygarmin application (this has to be rewritten as well)
- Deleted datum.py and refdatum.py (these might be worth a package on their own?)
- Deleted other unused files

**Comment by quentinsf** [comment]
That's brilliant - thanks!   I've merged it, and credited you in the README.   The only other change I've made is there is to comment that, while this is released on the terms of the GPLv3, earlier versions used GPLv2 and people may use it under those terms if they prefer.  (That seems fair, since all the past contributors including me were working with that license.)

I've added you as a contributor, so feel free to push further changes yourself!

All the best, 
Quentin

**Pull request merged**
